export const services = [
  {
    title: "Söz Organizasyonu",
    slug: "soz-organizasyonu",
    description: "En özel anınızı unutulmaz kılacak profesyonel söz organizasyonu hizmeti.",
    icon: "Ring",
    image: "/images/service-soz.jpg",
    longDescription: "Hayatınızın en özel anlarından biri olan söz töreniniz için, her detayı özenle planlıyoruz. Mekan dekorasyonundan ikramlara, fotoğraf çekiminden müzik seçimine kadar tüm süreci profesyonel ekibimizle yönetiyoruz.",
  },
  {
    title: "Nişan Organizasyonu",
    slug: "nisan-organizasyonu",
    description: "Hayalinizdeki nişan töreni için eksiksiz organizasyon çözümleri.",
    icon: "Celebration",
    image: "/images/service-nisan.jpg",
    longDescription: "Nişan töreninizi, sizin ve sevdiklerinizin unutamayacağı bir anıya dönüştürüyoruz. Klasik veya modern temalarda, açık veya kapalı mekan seçenekleriyle size özel çözümler sunuyoruz.",
  },
  {
    title: "Düğün Organizasyonu",
    slug: "dugun-organizasyonu",
    description: "Rüya gibi bir düğün için her detayı düşünen profesyonel ekip.",
    icon: "Heart",
    image: "/images/service-dugun.jpg",
    longDescription: "Hayallerinizdeki düğünü gerçeğe dönüştürmek için buradayız. Mekan seçiminden davetiye tasarımına, gelin buketinden pasta tasarımına kadar tüm detayları sizin için düşünüyoruz.",
  },
  {
    title: "Doğum Günü Organizasyonu",
    slug: "dogum-gunu-organizasyonu",
    description: "Her yaş için özel temalı doğum günü organizasyonları.",
    icon: "Cake",
    image: "/images/service-dogum-gunu.jpg",
    longDescription: "Çocuklarınızın doğum gününden sürpriz parti konseptlerine kadar her yaş grubuna özel temalı doğum günü organizasyonları düzenliyoruz.",
  },
  {
    title: "Sünnet Organizasyonu",
    slug: "sunnet-organizasyonu",
    description: "Geleneksel ve modern çizgide unutulmaz sünnet töreni organizasyonu.",
    icon: "Stars",
    image: "/images/sunnet.jpg",
    longDescription: "Sünnet töreninizi hem geleneksel hem de modern çizgide, ailenizin ve davetlilerinizin keyif alacağı şekilde organize ediyoruz.",
  },
  {
    title: "Açılış Organizasyonu",
    slug: "acilis-organizasyonu",
    description: "İşletmeniz için etkileyici açılış ve lansman organizasyonları.",
    icon: "Store",
    image: "/images/acilis.jpg",
    longDescription: "Markanızı en iyi şekilde tanıtmak için kurumsal açılış ve lansman organizasyonları düzenliyoruz. Davetli yönetiminden görsel şölene kadar profesyonel hizmet.",
  },
  {
    title: "Kokteyl Organizasyonu",
    slug: "kokteyl-organizasyonu",
    description: "Davetlerinize şıklık katan profesyonel kokteyl organizasyon hizmeti.",
    icon: "Glass",
    image: "/images/kokteyl.jpg",
    longDescription: "Kurumsal davetler, özel gün kutlamaları veya sosyal etkinlikleriniz için şık ve lezzetli kokteyl organizasyonları hazırlıyoruz.",
  },
  {
    title: "Balon Süsleme",
    slug: "balon-susleme",
    description: "Yaratıcı ve göz alıcı balon süsleme tasarımları.",
    icon: "Bubble",
    image: "/images/balon.jpg",
    longDescription: "Doğum günlerinden düğünlere, açılışlardan kurumsal etkinliklere kadar her tür organizasyon için yaratıcı balon süsleme hizmeti sunuyoruz.",
  },
  {
    title: "Sandalye Kiralama",
    slug: "sandalye-kiralama",
    description: "Her tür etkinlik için şık ve kaliteli sandalye kiralama hizmeti.",
    icon: "Armchair",
    image: "/images/sandalye.jpg",
    longDescription: "Organizasyonlarınıza şıklık katacak geniş sandalye kiralama seçeneklerimizle hizmetinizdeyiz. Farklı model ve renklerde sandalyeler.",
  },
  {
    title: "Asker Uğurlama",
    slug: "asker-ugurlama",
    description: "Asker uğurlama törenleriniz için coşkulu ve düzenli organizasyon.",
    icon: "Flag",
    image: "/images/asker.jpg",
    longDescription: "Sevdiklerinizi askere uğurlarken unutulmaz bir tören düzenlemek için profesyonel ekibimizle yanınızdayız.",
  },
  {
    title: "Mezuniyet Töreni",
    slug: "mezuniyet-toreni",
    description: "Mezuniyet sevincinizi profesyonel bir organizasyonla taçlandırın.",
    icon: "Graduation",
    image: "/images/mezuniyet.jpg",
    longDescription: "Okul mezuniyetlerinden kurumsal sertifika törenlerine kadar her tür mezuniyet organizasyonunda yanınızdayız.",
  },
];

export const siteConfig = {
  name: "Zahidem Organizasyon",
  description: "İstanbul'un her noktasında profesyonel organizasyon hizmeti. Söz, nişan, düğün, doğum günü ve daha fazlası.",
  phone: "+90 531 663 29 30",
  email: "info@zahidemorganizasyon.com",
  address: "İstanbul, Anadolu ve Avrupa Yakası",
  social: {
    instagram: "https://www.instagram.com/zahidemorganizasyon",
    facebook: "https://www.facebook.com/zahidemorganizasyonn",
    youtube: "https://www.youtube.com/channel/UCfSemzsL-ElAbQT3j_2xTaQ",
  },
};

export const districts = [
  "Arnavutköy", "Ataşehir", "Avcılar", "Bağcılar", "Bahçelievler",
  "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş", "Beylikdüzü",
  "Beyoğlu", "Büyükçekmece", "Beykoz", "Çatalca", "Çekmeköy",
  "Esenler", "Esenyurt", "Eyüp", "Fatih", "Gaziosmanpaşa",
  "Güngören", "Kadıköy", "Kağıthane", "Kartal", "Küçükçekmece",
  "Maltepe", "Pendik", "Sancaktepe", "Sarıyer", "Silivri",
  "Sultanbeyli", "Sultangazi", "Şile", "Şişli", "Tuzla",
  "Ümraniye", "Üsküdar", "Zeytinburnu",
];
