export const services = [
  {
    title: "Doğum Günü Organizasyonu",
    slug: "dogum-gunu-organizasyonu",
    description: "Her yaş için özel temalı doğum günü organizasyonları.",
    icon: "Cake",
    image: "/images/service-dogum-gunu.jpg",
    longDescription: "Çocuklarınızın doğum gününden sürpriz parti konseptlerine kadar her yaş grubuna özel temalı doğum günü organizasyonları düzenliyoruz.",
  },
  {
    title: "Mezuniyet",
    slug: "mezuniyet",
    description: "Mezuniyet sevincinizi profesyonel bir organizasyonla taçlandırın.",
    icon: "Graduation",
    image: "/images/mezuniyet.jpg",
    longDescription: "Okul mezuniyetlerinden kurumsal sertifika törenlerine kadar her tür mezuniyet organizasyonunda yanınızdayız.",
  },
  {
    title: "Söz & Nişan Konsepti",
    slug: "soz-nisan-konsepti",
    description: "En özel anınızı unutulmaz kılacak profesyonel söz ve nişan organizasyonu.",
    icon: "Ring",
    image: "/images/service-soz.jpg",
    longDescription: "Hayatınızın en özel anlarından biri olan söz ve nişan töreniniz için, her detayı özenle planlıyoruz. Mekan dekorasyonundan ikramlara, fotoğraf çekiminden müzik seçimine kadar tüm süreci profesyonel ekibimizle yönetiyoruz.",
  },
  {
    title: "Sevgililer Günü",
    slug: "sevgililer-gunu",
    description: "Sevdiklerinize unutulmaz bir Sevgililer Günü sürprizi.",
    icon: "Heart",
    image: "/images/service-dugun.jpg",
    longDescription: "Sevgililer Günü'nü özel kılmak için romantik mekan dekorasyonu, çiçek aranjmanları ve sürpriz organizasyonlar hazırlıyoruz.",
  },
  {
    title: "Açılış Organizasyonu",
    slug: "acilis-organizasyonu",
    description: "İşletmeniz için etkileyici açılış ve lansman organizasyonları.",
    icon: "Store",
    image: "/images/acilis.jpg",
    longDescription: "Markanızı en iyi şekilde tanıtmak için kurumsal açılış ve lansman organizasyonları düzenliyoruz. Davetli yönetiminden görsel şölene kadar profesyonel hizmet.",
  },
  {
    title: "Masa Sandalye Kiralama",
    slug: "masa-sandalye-kiralama",
    description: "Her tür etkinlik için şık ve kaliteli masa sandalye kiralama hizmeti.",
    icon: "Armchair",
    image: "/images/sandalye.jpg",
    longDescription: "Organizasyonlarınıza şıklık katacak geniş masa ve sandalye kiralama seçeneklerimizle hizmetinizdeyiz. Farklı model ve renklerde mobilyalar.",
  },
  {
    title: "Kokteyl Organizasyonu",
    slug: "kokteyl-organizasyonu",
    description: "Davetlerinize şıklık katan profesyonel kokteyl organizasyon hizmeti.",
    icon: "Glass",
    image: "/images/kokteyl.jpg",
    longDescription: "Kurumsal davetler, özel gün kutlamaları veya sosyal etkinlikleriniz için şık ve lezzetli kokteyl organizasyonları hazırlıyoruz.",
  },
  {
    title: "Yapay Ağaç Dekoru",
    slug: "yapay-agac-dekoru",
    description: "Mekanlarınıza doğal görünüm katan yapay ağaç dekorasyonları.",
    icon: "Stars",
    image: "/images/sunnet.jpg",
    longDescription: "İç ve dış mekanlarınız için gerçekçi yapay ağaç dekorasyonları ile doğanın güzelliğini her ortama taşıyoruz.",
  },
  {
    title: "Yapay Çiçek Dekoru",
    slug: "yapay-cicek-dekoru",
    description: "Bakım gerektirmeyen yapay çiçek aranjmanları ile kalıcı güzellik.",
    icon: "Celebration",
    image: "/images/service-nisan.jpg",
    longDescription: "Düğün, nişan, açılış ve özel etkinlikleriniz için profesyonel yapay çiçek dekorasyonları hazırlıyoruz.",
  },
  {
    title: "Piknik Organizasyonu",
    slug: "piknik-organizasyonu",
    description: "Açık havada unutulmaz piknik organizasyonları.",
    icon: "Flag",
    image: "/images/asker.jpg",
    longDescription: "Doğanın içinde özel piknik organizasyonları düzenliyoruz. Mekan hazırlığından ikramlara kadar her detayı düşünüyoruz.",
  },
  {
    title: "Sünnet Organizasyonu",
    slug: "sunnet-organizasyonu",
    description: "Geleneksel ve modern çizgide unutulmaz sünnet töreni organizasyonu.",
    icon: "Stars",
    image: "/images/sunnet.jpg",
    longDescription: "Sünnet töreninizi hem geleneksel hem de modern çizgide, ailenizin ve davetlilerinizin keyif alacağı şekilde organize ediyoruz.",
  },
  {
    title: "Balon Aranjmanı",
    slug: "balon-aranjmani",
    description: "Yaratıcı ve göz alıcı balon aranjman tasarımları.",
    icon: "Bubble",
    image: "/images/balon.jpg",
    longDescription: "Doğum günlerinden düğünlere, açılışlardan kurumsal etkinliklere kadar her tür organizasyon için yaratıcı balon aranjman hizmeti sunuyoruz.",
  },
];

export const siteConfig = {
  name: "Zahidem Organizasyon",
  description: "İstanbul'un her noktasında profesyonel organizasyon hizmeti. Söz, nişan, düğün, doğum günü ve daha fazlası.",
  phone: "+90 531 663 29 30",
  email: "info@zahidemorganizasyon.com",
  address: "İstanbul, Anadolu ve Avrupa Yakası",
  social: {
    instagram: "https://www.instagram.com/zahidemorganizasyon",
    facebook: "https://www.facebook.com/zahidemorganizasyonn",
    youtube: "https://www.youtube.com/channel/UCfSemzsL-ElAbQT3j_2xTaQ",
  },
};

export const districts = [
  "Arnavutköy", "Ataşehir", "Avcılar", "Bağcılar", "Bahçelievler",
  "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş", "Beylikdüzü",
  "Beyoğlu", "Büyükçekmece", "Beykoz", "Çatalca", "Çekmeköy",
  "Esenler", "Esenyurt", "Eyüp", "Fatih", "Gaziosmanpaşa",
  "Güngören", "Kadıköy", "Kağıthane", "Kartal", "Küçükçekmece",
  "Maltepe", "Pendik", "Sancaktepe", "Sarıyer", "Silivri",
  "Sultanbeyli", "Sultangazi", "Şile", "Şişli", "Tuzla",
  "Ümraniye", "Üsküdar", "Zeytinburnu",
];
